### PR TITLE
2.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #22 and #26 - provide for custom destructuring attributes through the `I*DestructuringAttribute` interfaces
 * #23 - reduce cache contention; use typical `Property = Value` syntax for `[LogMasked]`

### CODE REVIEW

**Comment by adamlith** [comment]
Shouldn't this PR be the 2.0.0 release?

**Comment by nblumhardt** [comment]
Oops! Nice catch :+1:

**Comment by nblumhardt** [comment]
Hoping for some feedback on the `-dev` versions, but otherwise I think it'd be great to release this ASAP.

**Comment by adamlith** [comment]
Have you received any feedback yet?

**Comment by nblumhardt** [comment]
None in the negative, so that's as good as positive! :-) Let's :shipit:

**Pull request merged**
