### PR TITLE
update to serilog 4.1.0

### PR DESCRIPTION
**Pull request by spaasis**
The current configuration is giving nuget warnings when using the newer serilog versions

### CODE REVIEW

**Comment by spaasis** [comment]
I'm not experienced in Serilog internals, but if there's more to here than just a simple package bump, I can try to work something out

**Comment by philippedurocher** [comment]
Is it possible to merge that PR to make the nuget warning go please? Thank you!

**Comment by sungam3r** [comment]
Waiting for #122 and #126.

**Comment by sungam3r** [comment]
@dependabot rebase

**Comment by sungam3r** [comment]
Thanks. Replaced by #129.

**Pull request closed without merging**
