### PR TITLE
Creating way to build more class level destructurers using attributes.

### PR DESCRIPTION
**Pull request by adamlith**
This PR should fix https://github.com/destructurama/attributed/issues/25

### CODE REVIEW

**Comment by nblumhardt** [comment]
I like the approach! :+1:

The only thing that doesn't sit quite right with me is the term "destructurer" used in the interface names... It's a bit unfortunate that we're stuck with the existing terminology...

What do you think about trying names like `ICreateLogEventProperty` and `ICreateLogEventPropertyValue`? Or some other names that have symmetry with the `TryXxxx()` method names on the interfaces?

**Comment by adamlith** [comment]
I agree about the names not being satisfactory. I also wich there was a way to make it apparent that you are only supposed to implement this interface on an attribute class.

But the problem I see is when someone wants to build thier own attribute, then it is far from obvious what the diferens is between ICreateLogEventProperty and ICreateLogEventPropertyValue. IClassXX vs IPropertyXXX does give the coder a hint about why those interfaces exist.

**Comment by nblumhardt** [comment]
:+1:

How about `IPropertyDestructuringAttribute` and `ITypeDestructuringAttribute`? (could potentially be applied to `struct`s as well as `class`es).

**Comment by nblumhardt** [comment]
:+1: awesome :-)

**Pull request merged**
